version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 10
    groups:
      gradle-updates:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/gradle"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 10
    groups:
      version-catalog-updates:
        patterns:
          - "libs.versions.toml"
