name: CI

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      manual_release:
        description: 'Perform a release'
        required: false
        default: false
        type: boolean

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '24'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build with Gradle
        run: |
          ./gradlew build

      - name: Do Release
        if: github.ref == 'refs/heads/main' || github.event.inputs.manual_release == 'true'
        run: |
          ./.github/scripts/perform-release.sh
